trigger:
- master
- release/*
- hotfix/*
- bugfix/*
- refactor/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  project_name: 'ProductManager'
  netcore_version: '3.1'
  sonarcloud_project: 'brunovitorprado_ProductManager'
  sonarcloud_organization: 'brunovitorprado'
  sonarcloud_account: 'ProductManager'
  docker_image_name: 'brunomcp2010/productmanager-api' 
  docker_registry_account: 'productmanager-api'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

jobs:
- job: Build
  steps:
  - script: echo "##vso[task.setvariable variable=sonarcloud_account;] mudei aqui"
    condition:  and(succeeded(), eq(variables['Build.SourceBranchName}}'], 'develop'))
    name: SetVars

  - script: echo $(sonarcloud_account)

  - script: |
      pwd && ls -la
      dotnet restore $(project_name)
      dotnet publish $(project_name) -c Release -o bin/Release/netcoreapp$(netcore_version)
      mkdir artifact
      cp -r $(System.DefaultWorkingDirectory)/bin/Release/netcoreapp$(netcore_version) artifact/$(Build.SourceBranchName)
    displayName: Build Application
  - task: PublishPipelineArtifact@1
    displayName: Store Application Artifact
    inputs:
      path: $(System.DefaultWorkingDirectory)/artifact
      artifact: $(project_name)

- job: UnityTests
  dependsOn: Build
  steps:
  - script: |
      dotnet tool install --global coverlet.console
      dotnet add $(project_name)/$(project_name).Test/$(project_name).Test.csproj package coverlet.msbuild
      dotnet add $(project_name)/$(project_name).Test/$(project_name).Test.csproj package XunitXml.TestLogger
      dotnet test /p:CollectCoverage=true \
                  /p:CoverletOutputFormat=\"opencover,cobertura\" \
                  /p:CoverletOutput=results/result \
                  /p:Exclude=[xunit.*]* $(project_name)/$(project_name).sln \
                  --test-adapter-path:. --logger:"xunit;LogFilePath=results/result.xunit.xml"
    displayName: Runnig Unit Tests

  - task:  PublishPipelineArtifact@1
    displayName: Store Test Result
    inputs:
      path: $(System.DefaultWorkingDirectory)/$(project_name)/$(project_name).Test/results
      artifact: UnitTestResults

  - task: PublishCodeCoverageResults@1
    displayName: Publish Code Coverage
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/$(project_name)/$(project_name).Test/results/result.cobertura.xml
      pathToSources: .
      failIfCoverageEmpty: true   

  - task: PublishTestResults@2
    displayName: Publish Test Result
    inputs:
      testResultsFormat: 'XUnit'
      testResultsFiles: '$(System.DefaultWorkingDirectory)/$(project_name)/$(project_name).Test/results/result.xunit.xml'
      testRunTitle: Collecting Test Results

- job: QualityAnalysis
  dependsOn: UnityTests
  steps:
    - task: DownloadPipelineArtifact@2
      displayName: Get Test Results
      inputs:
        artifact: UnitTestResults

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: '$(sonarcloud_account)'
        organization: '$(sonarcloud_organization)'
        scannerMode: 'MSBuild' 
        projectKey: '$(sonarcloud_project)'
        projectName: '$(project_name)'
        extraProperties: |
          sonar.cs.opencover.reportsPaths=$(Pipeline.Workspace)/result.opencover.xml 
          sonar.coverage.exclusions=$(project_name)/$(project_name).Api/**/*.*,$(project_name)/$(project_name).Infrastructure/**/*.*,$(project_name)/$(project_name).IoC/**/*.*               

    - script: |
        dotnet build $(project_name)
      displayName: Runing Build for Analysis

    - task: SonarCloudAnalyze@1
      displayName: Finish Sonar Analysis
      
    - task: SonarCloudPublish@1
      displayName: Publish quality gate results
      inputs:
        pollingTimeoutSec: '300'

- job: PublishDockerImage
  dependsOn: QualityAnalysis
  condition:  and(succeeded(), variables['Build.SourceBranch'], 'refs/heads/master')
  variables:
    Version: '$(Build.BuildNumber)'
  steps:
  - task: DownloadPipelineArtifact@2
    displayName: Get Application Artifact
    inputs:
      artifact: $(project_name)

  - script: |
      mkdir -p $(project_name)/bin/Release
      cp -r $(Pipeline.Workspace)/$(Build.SourceBranchName) $(project_name)/bin/Release/netcoreapp$(netcore_version)
    displayName: Prepare Files

  - task: Docker@2
    displayName: 'Build and Publish Docker Image'
    inputs:
      containerRegistry: '$(docker_registry_account)'
      repository: '$(docker_image_name)'
      command: 'buildAndPush'
      Dockerfile: '$(System.DefaultWorkingDirectory)/api.dockerfile'
      buildContext: '$(System.DefaultWorkingDirectory)'
      tags: |
        $(Version)
        latest
