CREATE DATABASE ProductManager
GO
USE ProductManager;
GO
CREATE TABLE Produtos (ID_PRODUTO UNIQUEIDENTIFIER, NOME_PRODUTO nvarchar(200), VALOR_PRODUTO decimal(18,2), IMAGEMURI_PRODUTO nvarchar(500));
GO